"""Initial Migration.

Revision ID: 083ab6b50593
Revises: 4332cd6ada2b
Create Date: 2022-05-11 06:43:55.424268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '083ab6b50593'
down_revision = '4332cd6ada2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('user_name', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'users', ['user_name'], ['id'])
    op.drop_column('comments', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'user_name')
    # ### end Alembic commands ###
