"""initial migration

Revision ID: 0ff86b8ea8e6
Revises: 0e5a29b7f68f
Create Date: 2022-05-09 21:19:01.139759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ff86b8ea8e6'
down_revision = '0e5a29b7f68f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('description', sa.String(), nullable=True))
    op.add_column('pitch', sa.Column('title', sa.String(), nullable=True))
    op.create_index(op.f('ix_pitch_description'), 'pitch', ['description'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pitch_description'), table_name='pitch')
    op.drop_column('pitch', 'title')
    op.drop_column('pitch', 'description')
    # ### end Alembic commands ###
